### ISSUE TITLE
Doesn't build on OS/X

### ISSUE THREAD

**Issue by nigelhorne** [jonahharris/osdb-typhoon#1]
os.c:149:19: error: use of undeclared identifier 'F_ULOCK'
        return lockf(fh, F_ULOCK, bytes);

**Comment by nigelhorne** [comment]
According to lockf(3), F_ULOCK is supported and defined in unistd.h.  I'm not sure what's going on here.

**Comment by jonahharris** [comment]
Damn feature test macros. Just remove the -D_POSIX_SOURCE from the src/Makefile CFLAGS

**Comment by jonahharris** [comment]
Fixed Makefile generation in 4bd7166597615175bc539fab4243a5d5836aa651

**Comment by nigelhorne** [comment]
I got it to build OK, but ddlp gives me an Abort trap with my own DDL file, but works OK with yours.  I need to investigate - the same DDL file compiles fine under Linux.  If I can work out what's wrong I'll submit a pull request.

**Comment by jonahharris** [comment]
Cool. Until today, I've never actually compiled it on OS X. I was going through my old open source database archive a couple weeks ago and couldn't easily find this on the web anymore, so I wanted to make sure I got it into github for people to find/use. I'm happy you found it!

**Comment by nigelhorne** [comment]
I used dbVista in the 1980s - pleased to Typhoon is back.  Pity there's no network database model stuff, but it's a great start and suitable for small applications.

**Comment by jonahharris** [comment]
I used dbVista as well. You should also check out https://github.com/jonahharris/osdb-dbstar -- which I kept a copy of before they closed-sourced it again and started working on getting it to compile on OS X last night :)
