### ISSUE TITLE
Cannot compile tyexport: multiple definition of `lex_file'

### ISSUE THREAD

**Issue by rchastain** [jonahharris/osdb-typhoon#6]
Hello! I tried to compile the project under Linux.

I had to convert line ending from CRLF to LF in _configure_. After that I ran _configure_ and _make_.

I get this error:
```
gcc -L../src exp.o export.o exportlx.o expspec.o -ltyphoon -o tyexport
/usr/bin/ld: exportlx.o:/home/roland/Documents/sources/typhoon/osdb-typhoon/util/exportlx.c:56: multiple definition of `lex_file'; export.o:/home/roland/Documents/sources/typhoon/osdb-typhoon/util/export.c:74: first defined here
```

**Comment by jonahharris** [comment]
It's compiling on OS X for me, even though there is a collision on those global vars - I assume it's related to different GCC's versions of common vars. Anyway, if you make it an extern in exportlx, rather than re-declared, I'd think it should work.

**Comment by rchastain** [comment]
Thank for your quick answer. Indeed, this solves the issue:
```
// exportlx.c
extern FILE	*lex_file;
```
```
// importlx.c
extern FILE	*lex_file;
```

**Comment by rchastain** [comment]
Thanks, I close the issue.
